### ISSUE TITLE
SMS not being sent

### ISSUE THREAD

**Issue by swedneck** [tijder/SmsMatrix#35]
on version 0.0.9 i can recieve messages fine, but sending does not work. This seems to be a regression from a previous version, where it worked fine.

**Comment by untidylamp** [comment]
it might be my change https://github.com/tijder/SmsMatrix/pull/31

can you post the error you get?

The change I made above is because messages with more than 160 characters were failing. the app would grab them from Matrix, try to send them and nothing no error, nothing. 

The above change uses "sendMultipartTextMessage" which works (for me) with messages less than 160 chars and greater than 160 chars.

**Comment by swedneck** [comment]
It seems it may have been an issue with synapse, as it crashed shortly after me experiencing this issue. Now that i restarted it i can send sms via matrix just fine.

**Comment by untidylamp** [comment]
Cool. If it's not a problem can you close this?

I'm more or less writing my own android app and using what I learn from that to fix this one. Eventually I'll send requests to catch errors and let the user know. I just need to learn how first.
